/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TedarikcilerRouteImport } from './routes/tedarikciler'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionsRouteImport } from './routes/productions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MusterilerRouteImport } from './routes/musteriler'
import { Route as MailRouteImport } from './routes/mail'
import { Route as KasaRouteImport } from './routes/kasa'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSunucuRouteImport } from './routes/settings_.sunucu'
import { Route as SettingsMailRouteImport } from './routes/settings_.mail'
import { Route as SettingsKurRouteImport } from './routes/settings_.kur'
import { Route as SettingsKullanicilarRouteImport } from './routes/settings_.kullanicilar'
import { Route as SettingsKategorilerRouteImport } from './routes/settings_.kategoriler'
import { Route as SettingsBildirimlerRouteImport } from './routes/settings_.bildirimler'
import { Route as SettingsBackupRouteImport } from './routes/settings_.backup'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as AuthSifreRouteImport } from './routes/auth_.sifre'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as PrintKindIdRouteImport } from './routes/print.$kind.$id'
import { Route as ApiPublicCronScanRouteImport } from './routes/api/public/cron-scan'

const TedarikcilerRoute = TedarikcilerRouteImport.update({
  id: '/tedarikciler',
  path: '/tedarikciler',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsRoute = ProductionsRouteImport.update({
  id: '/productions',
  path: '/productions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MusterilerRoute = MusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const KasaRoute = KasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSunucuRoute = SettingsSunucuRouteImport.update({
  id: '/settings_/sunucu',
  path: '/settings/sunucu',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMailRoute = SettingsMailRouteImport.update({
  id: '/settings_/mail',
  path: '/settings/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKurRoute = SettingsKurRouteImport.update({
  id: '/settings_/kur',
  path: '/settings/kur',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKullanicilarRoute = SettingsKullanicilarRouteImport.update({
  id: '/settings_/kullanicilar',
  path: '/settings/kullanicilar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKategorilerRoute = SettingsKategorilerRouteImport.update({
  id: '/settings_/kategoriler',
  path: '/settings/kategoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBildirimlerRoute = SettingsBildirimlerRouteImport.update({
  id: '/settings_/bildirimler',
  path: '/settings/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings_/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const AuthSifreRoute = AuthSifreRouteImport.update({
  id: '/auth_/sifre',
  path: '/auth/sifre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintKindIdRoute = PrintKindIdRouteImport.update({
  id: '/print/$kind/$id',
  path: '/print/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScanRoute = ApiPublicCronScanRouteImport.update({
  id: '/api/public/cron-scan',
  path: '/api/public/cron-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/kasa': typeof KasaRoute
  '/mail': typeof MailRoute
  '/musteriler': typeof MusterilerRoute
  '/notifications': typeof NotificationsRoute
  '/productions': typeof ProductionsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tedarikciler': typeof TedarikcilerRoute
  '/api/backup': typeof ApiBackupRoute
  '/auth/sifre': typeof AuthSifreRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/bildirimler': typeof SettingsBildirimlerRoute
  '/settings/kategoriler': typeof SettingsKategorilerRoute
  '/settings/kullanicilar': typeof SettingsKullanicilarRoute
  '/settings/kur': typeof SettingsKurRoute
  '/settings/mail': typeof SettingsMailRoute
  '/settings/sunucu': typeof SettingsSunucuRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/print/$kind/$id': typeof PrintKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/kasa': typeof KasaRoute
  '/mail': typeof MailRoute
  '/musteriler': typeof MusterilerRoute
  '/notifications': typeof NotificationsRoute
  '/productions': typeof ProductionsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tedarikciler': typeof TedarikcilerRoute
  '/api/backup': typeof ApiBackupRoute
  '/auth/sifre': typeof AuthSifreRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/bildirimler': typeof SettingsBildirimlerRoute
  '/settings/kategoriler': typeof SettingsKategorilerRoute
  '/settings/kullanicilar': typeof SettingsKullanicilarRoute
  '/settings/kur': typeof SettingsKurRoute
  '/settings/mail': typeof SettingsMailRoute
  '/settings/sunucu': typeof SettingsSunucuRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/print/$kind/$id': typeof PrintKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/auth': typeof AuthRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/invoices': typeof InvoicesRoute
  '/kasa': typeof KasaRoute
  '/mail': typeof MailRoute
  '/musteriler': typeof MusterilerRoute
  '/notifications': typeof NotificationsRoute
  '/productions': typeof ProductionsRoute
  '/products': typeof ProductsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tedarikciler': typeof TedarikcilerRoute
  '/api/backup': typeof ApiBackupRoute
  '/auth_/sifre': typeof AuthSifreRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/settings_/backup': typeof SettingsBackupRoute
  '/settings_/bildirimler': typeof SettingsBildirimlerRoute
  '/settings_/kategoriler': typeof SettingsKategorilerRoute
  '/settings_/kullanicilar': typeof SettingsKullanicilarRoute
  '/settings_/kur': typeof SettingsKurRoute
  '/settings_/mail': typeof SettingsMailRoute
  '/settings_/sunucu': typeof SettingsSunucuRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/print/$kind/$id': typeof PrintKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/auth'
    | '/companies'
    | '/expenses'
    | '/files'
    | '/invoices'
    | '/kasa'
    | '/mail'
    | '/musteriler'
    | '/notifications'
    | '/productions'
    | '/products'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/tedarikciler'
    | '/api/backup'
    | '/auth/sifre'
    | '/companies/$id'
    | '/settings/backup'
    | '/settings/bildirimler'
    | '/settings/kategoriler'
    | '/settings/kullanicilar'
    | '/settings/kur'
    | '/settings/mail'
    | '/settings/sunucu'
    | '/api/public/cron-scan'
    | '/print/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/auth'
    | '/companies'
    | '/expenses'
    | '/files'
    | '/invoices'
    | '/kasa'
    | '/mail'
    | '/musteriler'
    | '/notifications'
    | '/productions'
    | '/products'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/tedarikciler'
    | '/api/backup'
    | '/auth/sifre'
    | '/companies/$id'
    | '/settings/backup'
    | '/settings/bildirimler'
    | '/settings/kategoriler'
    | '/settings/kullanicilar'
    | '/settings/kur'
    | '/settings/mail'
    | '/settings/sunucu'
    | '/api/public/cron-scan'
    | '/print/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/auth'
    | '/companies'
    | '/expenses'
    | '/files'
    | '/invoices'
    | '/kasa'
    | '/mail'
    | '/musteriler'
    | '/notifications'
    | '/productions'
    | '/products'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/tedarikciler'
    | '/api/backup'
    | '/auth_/sifre'
    | '/companies/$id'
    | '/settings_/backup'
    | '/settings_/bildirimler'
    | '/settings_/kategoriler'
    | '/settings_/kullanicilar'
    | '/settings_/kur'
    | '/settings_/mail'
    | '/settings_/sunucu'
    | '/api/public/cron-scan'
    | '/print/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AuthRoute: typeof AuthRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  FilesRoute: typeof FilesRoute
  InvoicesRoute: typeof InvoicesRoute
  KasaRoute: typeof KasaRoute
  MailRoute: typeof MailRoute
  MusterilerRoute: typeof MusterilerRoute
  NotificationsRoute: typeof NotificationsRoute
  ProductionsRoute: typeof ProductionsRoute
  ProductsRoute: typeof ProductsRoute
  QuotesRoute: typeof QuotesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TedarikcilerRoute: typeof TedarikcilerRoute
  ApiBackupRoute: typeof ApiBackupRoute
  AuthSifreRoute: typeof AuthSifreRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsBildirimlerRoute: typeof SettingsBildirimlerRoute
  SettingsKategorilerRoute: typeof SettingsKategorilerRoute
  SettingsKullanicilarRoute: typeof SettingsKullanicilarRoute
  SettingsKurRoute: typeof SettingsKurRoute
  SettingsMailRoute: typeof SettingsMailRoute
  SettingsSunucuRoute: typeof SettingsSunucuRoute
  ApiPublicCronScanRoute: typeof ApiPublicCronScanRoute
  PrintKindIdRoute: typeof PrintKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tedarikciler': {
      id: '/tedarikciler'
      path: '/tedarikciler'
      fullPath: '/tedarikciler'
      preLoaderRoute: typeof TedarikcilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions': {
      id: '/productions'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof ProductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musteriler': {
      id: '/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof MusterilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasa': {
      id: '/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof KasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/sunucu': {
      id: '/settings_/sunucu'
      path: '/settings/sunucu'
      fullPath: '/settings/sunucu'
      preLoaderRoute: typeof SettingsSunucuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/mail': {
      id: '/settings_/mail'
      path: '/settings/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof SettingsMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/kur': {
      id: '/settings_/kur'
      path: '/settings/kur'
      fullPath: '/settings/kur'
      preLoaderRoute: typeof SettingsKurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/kullanicilar': {
      id: '/settings_/kullanicilar'
      path: '/settings/kullanicilar'
      fullPath: '/settings/kullanicilar'
      preLoaderRoute: typeof SettingsKullanicilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/kategoriler': {
      id: '/settings_/kategoriler'
      path: '/settings/kategoriler'
      fullPath: '/settings/kategoriler'
      preLoaderRoute: typeof SettingsKategorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/bildirimler': {
      id: '/settings_/bildirimler'
      path: '/settings/bildirimler'
      fullPath: '/settings/bildirimler'
      preLoaderRoute: typeof SettingsBildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/backup': {
      id: '/settings_/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/auth_/sifre': {
      id: '/auth_/sifre'
      path: '/auth/sifre'
      fullPath: '/auth/sifre'
      preLoaderRoute: typeof AuthSifreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$kind/$id': {
      id: '/print/$kind/$id'
      path: '/print/$kind/$id'
      fullPath: '/print/$kind/$id'
      preLoaderRoute: typeof PrintKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-scan': {
      id: '/api/public/cron-scan'
      path: '/api/public/cron-scan'
      fullPath: '/api/public/cron-scan'
      preLoaderRoute: typeof ApiPublicCronScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AuthRoute: AuthRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  FilesRoute: FilesRoute,
  InvoicesRoute: InvoicesRoute,
  KasaRoute: KasaRoute,
  MailRoute: MailRoute,
  MusterilerRoute: MusterilerRoute,
  NotificationsRoute: NotificationsRoute,
  ProductionsRoute: ProductionsRoute,
  ProductsRoute: ProductsRoute,
  QuotesRoute: QuotesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TedarikcilerRoute: TedarikcilerRoute,
  ApiBackupRoute: ApiBackupRoute,
  AuthSifreRoute: AuthSifreRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsBildirimlerRoute: SettingsBildirimlerRoute,
  SettingsKategorilerRoute: SettingsKategorilerRoute,
  SettingsKullanicilarRoute: SettingsKullanicilarRoute,
  SettingsKurRoute: SettingsKurRoute,
  SettingsMailRoute: SettingsMailRoute,
  SettingsSunucuRoute: SettingsSunucuRoute,
  ApiPublicCronScanRoute: ApiPublicCronScanRoute,
  PrintKindIdRoute: PrintKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
